apiVersion: v1
kind: Service
metadata:
 name: helloworld
 labels:
  name: helloworld
  app: helloworld
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 80
 selector:
   app: helloworld
