apiVersion: apps/v1
kind: Deployment
metadata: 
 name: second-hello-deployment
 labels: 
  app: helloworld
  version: v2
spec:
 replicas: 1
 template:
  metadata:
   name: hello-world-2
   labels:
    tier: tier2
  spec:
   containers:
    - name: hello2
      image: hello-world-2
 selector:
  matchLabels:
   tier: tier2